[package]
name = "pmg-rs"
version = "0.6.2"
authors = [
    "Proxmox Support Team <support@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
    "Fabian Ebner <f.ebner@proxmox.com>",
]
edition = "2018"
license = "AGPL-3"
description = "PMG parts which have been ported to rust"
exclude = [
    "build",
    "debian",
    "PMG",
]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
hex.workspace = true
http.workspace = true
libc.workspace = true
nix.workspace = true
openssl.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
url.workspace = true

perlmod.workspace = true

proxmox-acme-rs.workspace = true
proxmox-apt.workspace = true
proxmox-http.workspace = true
proxmox-subscription.workspace = true
proxmox-sys.workspace = true
proxmox-tfa.workspace = true
proxmox-time.workspace = true
