[package]
name = "pmg-rs"
version = "0.6.1"
authors = [
    "Proxmox Support Team <support@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
    "Fabian Ebner <f.ebner@proxmox.com>",
]
edition = "2018"
license = "AGPL-3"
description = "PMG parts which have been ported to rust"
exclude = [
    "build",
    "debian",
    "PMG",
]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0"
hex = "0.4"
http = "0.2.7"
libc = "0.2"
nix = "0.24"
openssl = "0.10.40"
serde = "1.0"
serde_bytes = "0.11.3"
serde_json = "1.0"
ureq = { version = "2.4", features = ["native-certs"] }
url = "2"

perlmod = { version = "0.13", features = [ "exporter" ] }

proxmox-acme-rs = { version = "0.4", features = ["client"] }
proxmox-apt = "0.9"
proxmox-http = { version = "0.6.4", features = ["client-trait"] }
proxmox-subscription = "0.2"
proxmox-sys = "0.3"
proxmox-tfa = { version = "2.1", features = ["api"] }
proxmox-time = "1.1.3"
