[package]
name = "pve-rs"
version = "0.6.2"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "PVE parts which have been ported to Rust"
homepage = "https://www.proxmox.com"

exclude = [
    "debian",
]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.13"
hex = "0.4"
http = "0.2.7"
libc = "0.2"
nix = "0.24"
openssl = "0.10.40"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
ureq = { version = "2.4", features = ["native-certs"] }
url = "2"

perlmod = { version = "0.13", features = [ "exporter" ] }

proxmox-apt = "0.9"
proxmox-http = { version = "0.6.3", features = ["client-trait"] }
proxmox-openid = "0.9.5"
proxmox-subscription = "0.2"
proxmox-sys = "0.3"
proxmox-tfa = { version = "2", features = ["api"] }
proxmox-time = "1.1.3"
