[package]
name = "pve-rs"
version = "0.7.3"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "PVE parts which have been ported to Rust"
homepage = "https://www.proxmox.com"

exclude = [
    "debian",
]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow.workspace = true
base32.workspace = true
base64.workspace = true
env_logger.workspace = true
hex.workspace = true
http.workspace = true
libc.workspace = true
nix.workspace = true
openssl.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
url.workspace = true

perlmod.workspace = true

proxmox-apt.workspace = true
proxmox-http.workspace = true
proxmox-openid.workspace = true
proxmox-resource-scheduling.workspace = true
proxmox-subscription.workspace = true
proxmox-sys.workspace = true
proxmox-tfa.workspace = true
proxmox-time.workspace = true
