[package]
name = "pve-rs"
version = "0.3.1"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "PVE parts which have been ported to Rust"
homepage = "https://www.proxmox.com"

exclude = [
    "debian",
]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.12"
hex = "0.4"
libc = "0.2"
nix = "0.19"
openssl = "0.10"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"

perlmod = { version = "0.8.1", features = [ "exporter" ] }

proxmox-apt = "0.8"
proxmox-openid = "0.8"

#proxmox-tfa-api = { path = "../proxmox-tfa-api", version = "0.1" }

# Dependencies purely in proxmox-tfa-api:
webauthn-rs = "0.2.5"
proxmox-time = "1"
proxmox-uuid = "1"
proxmox-tfa = { version = "1.2", features = ["u2f"] }
